version: "3"

services:
  versync:
    image: unwenliu/verysync:1.2.4
    ports:
      - "3000:3000"
      - "8886:8886"
    volumes:
      - "/root/docker_app/docker_verysync/data:/data"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped
